name: ee_commerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  iconsax: ^0.0.8                     # Gói cung cấp bộ icon Iconsax
  cupertino_icons: ^1.0.6             # Icon theo phong cách Cupertino

  # State management
  get: ^4.6.6                         # Quản lý trạng thái với GetX
  get_storage: ^2.1.1                 # Lưu trữ dữ liệu trên thiết bị với GetX
  bloc: ^8.1.4                        # Quản lý trạng thái với Bloc
  flutter_bloc: ^8.1.6                # Bloc cho Flutter

  # UI/UX Enhancements
  flutter_screenutil: ^5.9.3          # Hỗ trợ thiết kế giao diện Responsive
  velocity_x: ^4.2.1                  # Thư viện hỗ trợ xây dựng giao diện nhanh chóng
  smooth_page_indicator: ^1.1.0       # Hiệu ứng chuyển trang mượt mà
  carousel_slider: ^4.2.1             # Slider hình ảnh cho carousel
  readmore: ^3.0.0                    # Đọc thêm hoặc thu gọn nội dung văn bản
  flutter_rating_bar: ^4.0.1          # Thanh đánh giá rating bar

  # Networking
  http: ^1.2.1                        # HTTP requests
  url_launcher: ^6.3.0                # Mở URL hoặc ứng dụng khác từ app

  # Internationalization
  intl: ^0.19.0                       # Hỗ trợ đa ngôn ngữ

  # Logging
  logger: ^2.3.0                      # Thư viện hỗ trợ ghi log

  # Firebase
  firebase_core: ^3.4.0               # Cốt lõi của Firebase

  # Splash Screen
  flutter_native_splash: ^2.4.0       # Tạo splash screen cho ứng dụng

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0               # Bộ quy tắc linting cho Flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/brands/
    - lib/main.dart
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800